title: Länsi-Uudenmaan Tanssijat ry
email: lu.tanssijat@gmail.com
description: > # Länsi-Uudenmaan tanssijat ry on lavatanssijoiden seura.
baseurl: ""
url: "http://lutanssijat.fi"
facebook_username: Länsi-Uudenmaan-Tanssijat-Ry-945136225616395
twitter_username:
github_username:
logo: content/images/lutanssijat_transparent_logo.png
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
